[package]
name = "model"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["serde"] }
hex = { version = "0.4", default-features = false }
primitive-types = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "1.6", default-features = false }

[dev-dependencies]
serde_json = "1.0"
