[package]
name = "serde-ext"
version = "0.1.0"
authors = ["Cow Protocol Developers <dev@cow.fi>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
alloy = { workspace = true }
const-hex = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }