[package]
name = "order-validation"
version = "0.1.0"
authors = ["Cow Protocol Developers <dev@cow.fi>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
alloy = { workspace = true }
contracts = { workspace = true }
moka = { workspace = true, features = ["sync"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
futures = {workspace = true }

[lints]
workspace = true
