chain-id = "31337" # Anvil local chain
base-tokens = [
    "0x5FbDB2315678afecb367f032d93F642f64180aa3", # WETH
    "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9", # DAI
    "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0", # USDC
]
max-hops = 2
max-partial-attempts = 5
native-token-price-estimation-amount = "100000000000000000" # 0.1 ETH
