[package]
name = "openapi-generator"
version = "0.1.0"
authors = ["Cow Protocol Developers <dev@cow.fi>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]

[build-dependencies]
solvers = { path = "../solvers" }
