[package]
name = "euler-solver"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "euler-solver"
path = "src/main.rs"

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
bigdecimal = { workspace = true }
chain = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
const-hex = { workspace = true }
contracts = { workspace = true }
ethrpc = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solvers-dto = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
#observe = { workspace = true, features = ["axum-tracing"] }
chrono = { workspace = true, features = ["serde"] }

[lints]
workspace = true
