[package]
name = "solvers-dto"
version = "0.1.0"
authors = ["Cow Protocol Developers <dev@cow.fi>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
bytes-hex = { workspace = true } # may get marked as unused but it's used with serde
app-data = { workspace = true }
bigdecimal = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
const-hex = { workspace = true }
number = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
web3 = { workspace = true }

[lints]
workspace = true
