[package]
name = "number"
version = "0.1.0"
authors = ["Cow Protocol Developers <dev@cow.fi>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
bigdecimal = { workspace = true }
derive_more = "0.99.0"
num = { workspace = true }
primitive-types = { workspace = true }
serde_with = { workspace = true }
serde = { workspace = true }
uint = "0.9.4"

[dev-dependencies]
serde_json = "1.0.114"
