[package]
name = "number"
version = "0.1.0"
authors = ["Cow Protocol Developers <dev@cow.fi>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
alloy = { workspace = true, features = ["serde"] }
ruint = { workspace = true, features = ["num-bigint"] }
bigdecimal = { workspace = true }
num = { workspace = true }
serde_with = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
