[package]
name = "model"
version = "0.1.0"
authors = ["Gnosis Developers <developers@gnosis.io>", "Cow Protocol Developers <dev@cow.fi>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
app-data = { path = "../app-data" }
bytes-hex = { path = "../bytes-hex" }
bigdecimal = { workspace = true }
chrono = { workspace = true, features = ["serde", "clock"] }
derivative = { workspace = true }
hex = { workspace = true, default-features = false }
hex-literal = { workspace = true }
lazy_static = { workspace = true }
number = { path = "../number" }
num = { workspace = true }
primitive-types = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
web3 = { workspace = true, features = ["signing"] }

[dev-dependencies]
serde_json = { workspace = true }
shared = { path = "../shared" }
maplit = { workspace = true }
testlib = { path = "../testlib" }

[features]
e2e = []

[lints]
workspace = true
