[package]
name = "model"
version = "0.1.0"
authors = ["Gnosis Developers <developers@gnosis.io>", "Cow Protocol Developers <dev@cow.fi>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
alloy = { workspace = true, features = ["sol-types", "signers", "signer-local", "rand"] }
anyhow = { workspace = true }
app-data = { workspace = true }
bigdecimal = { workspace = true }
bytes-hex = { workspace = true }
chrono = { workspace = true, features = ["serde", "clock"] }
const-hex = { workspace = true }
derive_more = { workspace = true }
hex-literal = { workspace = true }
num = { workspace = true }
number = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }

[dev-dependencies]
maplit = { workspace = true }
testlib = { workspace = true }

[features]
e2e = []

[lints]
workspace = true
