[[drivers]]
name = "baseline"
url = "http://driver/baseline"
submission-account.address = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"

[[drivers]]
name = "baseline2"
url = "http://driver2/baseline2"
submission-account.address = "0x14dC79964da2C08b23698B3D3cc7Ca32193d9955"

[fee-policies]
