[package]
name = "app-data"
version = "0.1.0"
edition = "2021"

[dependencies]
app-data-hash = { path = "../app-data-hash" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
primitive-types = { workspace = true }
hex = "0.4.3"

[dev-dependencies]
ethcontract = { workspace = true }

[features]
test_helpers = []
