[package]
name = "solver"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
model = { path = "../model" }
primitive-types = "0.7"
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features =[ "macros"] }
