[package]
name = "solver"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
contracts = { path = "../contracts" }
futures = "0.3"
jsonrpc-core = "14.0"
maplit = "1.0"
model = { path = "../model" }
primitive-types = "0.7"
reqwest = { version = "0.10", features = ["json"] }
serde_json = "1.0"
tokio = { version = "0.2", features =[ "macros", "time"] }
tracing = "0.1"
tracing-setup = { path = "../tracing-setup" }
web3 = { version = "0.13", default-features = false }
