[package]
name = "solver"
version = "0.1.0"
edition = "2018"

[lib]
name = "solver"
path = "src/lib.rs"

[[bin]]
name = "solver"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
contracts = { path = "../contracts" }
ethcontract = { version = "0.9", default-features = false }
futures = "0.3"
hex = "0.4"
hex-literal = "0.3"
jsonrpc-core = "14.0"
maplit = "1.0"
model = { path = "../model" }
num = "0.3"
primitive-types = "0.7"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shared-arguments = { path = "../shared-arguments" }
structopt = { version = "0.3" }
tokio = { version = "0.2", features =[ "macros", "time"] }
tracing = "0.1"
tracing-setup = { path = "../tracing-setup" }
web3 = { version = "0.13", default-features = false, features = ["http-tls"] }

[dev-dependencies]
tracing-subscriber = "0.2"
