
name: deploy
on:
  push:
    branches: [main]
    tags: [v*]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Services image metadata
        id: meta_services
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later
      - name: Services image build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.binary
          push: true
          tags: ${{ steps.meta_services.outputs.tags }}
          labels: ${{ steps.meta_services.outputs.labels }}

      - name: Migration image metadata
        id: meta_migration
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-migration
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later
      - name: Migration image build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.migration
          push: true
          tags: ${{ steps.meta_migration.outputs.tags }}
          labels: ${{ steps.meta_migration.outputs.labels }}

      - uses: cowprotocol/autodeploy-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          pods: dfusion-v2-api-rinkeby,dfusion-v2-solver-rinkeby,dfusion-v2-api-mainnet,dfusion-v2-solver-mainnet,dfusion-v2-api-xdai,dfusion-v2-solver-xdai,dfusion-v2-solver-shadow,dfusion-v2-alerter-mainnet
          tag: ${{ secrets.AUTODEPLOY_TAG }}
          url: ${{ secrets.AUTODEPLOY_URL }}
          token: ${{ secrets.AUTODEPLOY_TOKEN }}
